language: generic
sudo: true
dist: trusty
addons:
  apt:
    packages:
    - python3-setuptools
    - python3-all
    - python3-pip
    - debhelper
    - build-essential
before_install:
 - apt-get update
 - apt-get install -y python3-setuptools python3-all python3-pip debhelper build-essential python3-pip
install:
  - pip3 install .
script:
  - nosetests
after_success:
  - dpkg-buildpackage
  - mv ../*.deb .
deploy:
  provider: bintray
  file: descriptor.json
  user: gijzelaerr
  key:
    secure: or71RwHHnymKhZeoxATCyZq/iorV14Uv6Rwomkf4x2yj2QWgsMCNNsRfmjiEu8dmZmDH9gyjPdebNfdg6VEZqsNbNBWlvCD81lKBFqaEO3IBKhEwDOcJtHFHmJGIJWvN5jnwKa8usX56pQF5gEbFkg9X+RFwHDpd7OUIJfYweUfG2P68DlKxwWhakDTqYi+MUO/l5GKE+mkgupPsgafYabu9O/cVGkutZCwy6WJi0UGg7Fnanas9q986927zzFjTPpx2IZW14URsSnrXilqaVEyoBF8Hs2gG4gzCIEb00Q3/WrNZMYtX19/OnB+7i6JFes9kdCafD+N3Hewm5KtP+wM5or7HVZrff2DrgxS+jcnR4zYYL8elVMy7nuQeeSoLVoWcm+k+Dd6lDIbZJPyOXkZ4hftS1xgnLgXbdoRo2ag7VAZU8AtBhhzIjSAv1HgffE8FNHsCUx3vUQdb+sKdZMuuqIlT175n8T9X/txzqMIFqdCChStrTLJq60V/PdnIRHHKWsAwXoun8wuEWPN0ttHRJAApmi2q43E4MkeQd7TyZXyhNBd2WHIcAWdd3C779EImrZKRm/gnfteQCP8AstGR9BC5Jn/mO1XDP4mR1EkAG6BmJ1lpWWyGtWK12U7DeVbnpqnRzq0auBIOKf/GbskHf91jqQgn0bRE/IatWq8=
